---
name: Cloning repo to server

on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pulling latest changes from repo
      uses: appleboy/ssh-action@v0.1.10
      env:
        TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        DEV_ID: ${{ secrets.TELEGRAM_DEVELOPER_ID }}
        MANAGER_ID: ${{ secrets.TELEGRAM_MANAGER_ID }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: TOKEN,DEV_ID,MANAGER_ID
        script: |
          [ -d "money-bot" ] || git clone git@github.com:WannaFight/money-bot.git
          cd money-bot
          git pull origin master
          echo "TELEGRAM_BOT_TOKEN=$TOKEN" > .env
          echo "TELEGRAM_DEVELOPER_ID=$DEV_ID" >> .env
          echo "TELEGRAM_MANAGER_ID=$MANAGER_ID" >> .env

    - name: Start service
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd money-bot
          docker build --no-cache .
          docker-compose build --no-cache
          docker-compose up --force-recreate -d